development:
  adapter: postgresql
  encoding: unicode
  database: aaa777_development
  pool: 5
  username: ubuntu0
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: aaa777_test
  pool: 5
  username: ubuntu0
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: aaa777_production
  pool: 5
  username: ubuntu0
  password: