development:
  adapter: postgresql
  encoding: unicode
  database: mysterious-taiga-8033_development
  pool: 5
  username: ubuntu0
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: mysterious-taiga-8033_test
  pool: 5
  username: ubuntu0
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: mysterious-taiga-8033_production
  pool: 5
  username: ubuntu0
  password: